import streamlit as st
import pandas as pd
from datetime import datetime
import oauth
import llm_manager
import invoice_manager
from app_logger import get_logger

logger = get_logger(__name__)

# ==============================================================================
# MAIN INTERFACE
# ==============================================================================

def ensure_user_login():
    """Checks login status and halts execution if not logged in."""
    if "creds" not in st.session_state:
        st.warning("Please log in to use the Chat Bot.")
        oauth.ensure_google_login(show_ui=True)
        if "creds" not in st.session_state:
            st.stop()
            
    user_email = st.session_state.get("user_email")
    if not user_email:
        st.error("Authentication Error: User email missing.")
        st.stop()
        
    return user_email

def run_chat_interface():
    """Main entry point for the Chat Bot view."""
    
    st.title("📊 AI Invoice Assistant")
    st.caption("Ask questions about your finances, e.g., 'How much did I spend in 2024?'")
    
    # 1. Login Check
    user_email = ensure_user_login()
    
    # 2. Load Data
    invoices = invoice_manager.load_invoices_from_db(user_email)
    st.toast(f"Loaded {len(invoices)} invoices.", icon="✅")
    
    # 3. Query Input
    query = st.text_input("Message", placeholder="Type your question here...")
    
    if st.button("Send", type="primary") and query:
        with st.spinner("Thinking..."):
            # A. Extract Intent
            params = llm_manager.extract_filter_parameters(query)
            
            if not params:
                st.error("I couldn't understand that query. Please try being more specific about dates or categories.")
                return

            filtered_invoices = []
            min_inv, max_inv = None, None
            
            # B. Execute Filtering
            invoice_no = params.get("invoice_no")
            
            if invoice_no:
                # Specific Invoice Search
                st.info(f"Searching for Invoice #{invoice_no}")
                filtered_invoices = invoice_manager.filter_by_invoice_number(invoices, invoice_no)
            
            elif params.get("start_date") and params.get("end_date"):
                # Date Range Search
                try:
                    start = datetime.strptime(params["start_date"], "%b %d %Y")
                    end = datetime.strptime(params["end_date"], "%b %d %Y")
                    
                    filtered_invoices, min_inv, max_inv = invoice_manager.filter_by_date_and_category(
                        invoices, start, end, params.get("category")
                    )
                    st.info(f"Filtered {len(filtered_invoices)} invoices from {start.strftime('%b %d, %Y')} to {end.strftime('%b %d, %Y')}")
                except ValueError:
                    st.error("Date parsing failed. Please try a clearer date format.")
                    return
            else:
                # Default case (e.g. "Show me all")
                filtered_invoices = invoices

            # C. Synthesize Answer
            if not filtered_invoices:
                st.warning("No invoices match your criteria.")
            else:
                total_val = invoice_manager.calculate_total_amount(filtered_invoices)
                answer, model_used = llm_manager.generate_human_response(query, filtered_invoices, total_val, min_inv, max_inv)
                
                st.markdown("### 🤖 Answer")
                st.write(answer)
                st.caption(f"Generated by: {model_used}")
                
                with st.expander(f"View {len(filtered_invoices)} Source Documents"):
                    st.dataframe(pd.DataFrame(filtered_invoices))
